markdown: kramdown
permalink: /:title
url: "http://nodeschool.io/montreal"
timezone: America/Montreal

languages: ["en", "fr"]
exclude_from_localizations: ["fonts", "i", "js", "node_modules", "package.json",
"favicon.ico", "Gemfile", "Gemfile.lock", "robots.txt"]

kramdown:
  input: GFM

# Use the following plug-ins
gems:
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
  - .editorconfig
  - Procfile
  - .sass-cache/
  - tasks/

mentors:
  - name: pcuci
    display: 'Paul Cuciureanu'
    twitter: pcuci
  - name: cassie
    display: 'Cassie L. Rhéaume'
    twitter: cassierheaume
  - name: david
    display: 'David Rowley'
    twitter: davidrowley514
  - name: valeri
    display: 'Valeri Vicneanschi'
    twitter: vicneanschi
  - name: andre-john
    display: 'André John Mas'
    twitter: ajmas
  - name: harris
    display: 'Harris Robin Kalash'
    twitter: LulzHRK
  - name: shawn
    display: 'Shawn Thmpson'
    twitter: plansmash
  - name: nicolas
    display: 'Nicolas Géré'
    twitter: nicolasgere
  - name: fharper
    display: 'Frédéric Harper'
    twitter: fharper
  - name: rsayar
    display: 'Rami Sayar'
    twitter: ramisayar
  - name: matan
    display: 'Matan Kushner'
    twitter: matchai
